name: pay_example
description: Shows how to use the pay plugin.
publish_to: 'none'
version: 1.0.0+01

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  pay: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
#    - assets/images/tablet/
#    - assets/images/phone/
#    - assets/images/other/
